
// Generated by https://quicktype.io
export type ServerBoard = Array<number[]>;

export interface ServerBoardResponse {
  board: ServerBoard
  solutionBoard: ServerBoard
}

// response for the /validate call
export interface ServerBoardValidationResponse {
  status: ServerBoardValidationStatus
}

export enum ServerBoardValidationStatus {
  BROKEN = 'broken',
  SOLVED = 'solved',
  UNSOLVED = 'unsolved'
}

export enum ServerBoardDifficulty {
  BEGINNER = 'beginner',
  EASY = 'easy',
  MEDIUM = 'medium',
  HARD = 'hard',
  EXTREME = 'extreme',
  RANDOM = 'random'
}

