
// Generated by https://quicktype.io
export type ServerBoard = Array<number[]>;

export interface ServerBoardResponse {
  board: ServerBoard;
}

export interface ServerBoardValidationResponse {
  status: ServerBoardValidationStatus;
}

export enum ServerBoardValidationStatus {
  BROKEN = 'broken',
  SOLVED = 'solved',
  UNSOLVED = 'unsolved'
}